In [13]:
import urllib.request as req
from bs4 import BeautifulSoup
from urllib.request import urlopen

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import matplotlib.font_manager as fm
font_name=fm.FontProperties(fname="C:\\Windows\\Fonts\\malgun.ttf ").get_name()
plt.rc("font", family=font_name)

import matplotlib as mlp
mlp.rcParams["axes.unicode_minus"]=False

import requests

In [14]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
from sklearn.neighbors import KNeighborsClassifier

## KNN

- K-Nearest Neighbors
- 이해하기 쉽고 직관적인 모델
- 더 복잡한 알고리즘을 적용하기 전에 시도해 볼 수 있는 알고리즘
- 훈련셋이 너무 크면 예측이 느려진다

## 1. 동작원리

In [2]:
! pip install mglearn

In [15]:
import mglearn

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [10]:
from sklearn.neighbors import KNe

ImportError: cannot import name 'KNe' from 'sklearn.neighbors' (C:\Users\user\Anaconda3\lib\site-packages\sklearn\neighbors\__init__.py)

In [6]:
X, y = mglearn.datasets.make_forge()
mglearn.discrete_scatter(X[:,0], X[:, 1], y)

NameError: name 'mglearn' is not defined

In [4]:
mglearn.plots.plot_knn_classification()

NameError: name 'mglearn' is not defined

## 거리 측정 방식(norm)

- norm: 벡터의 크기 또는 길이 측정 시 사용하는 개념

### (1) L1 Norm

- 단순한 거리의 절대값이 합
- 맨하탄 거리

### (2) L2 Norm

- 거리의 절대값의 합에 루트 적용
- 피타고라스의 정리, 유클리드 거리

## 사용 예1

In [13]:
df = pd.DataFrame(np.random.randint(1,10,(3,2)))
df.columns = ["x", "y"]
df

x  y
0  9  7
1  2  3
2  5  4

In [15]:
sns.lmplot("x", "y", data=df, fit_reg=False)

TypeError: lmplot() got multiple values for argument 'data'

In [16]:
# (0,0)으로부터 어디가 제일 가까울까?

np.linalg.norm(df.values, ord=2, axis=1)

array([11.40175425,  3.60555128,  6.40312424])

## 사용예2

In [18]:
df = pd.DataFrame(np.random.randint(-3,3,(3,3)))
df.columns = ["move1", "move2", "move3"]
df

move1  move2  move3
0     -1      2      2
1      0     -1      2
2     -2      0     -2

In [20]:
# 3명이 3번의 주사위를 던져서 걸음수를 측정했을 때, 누가 제일 많이 걸었을까?

np.linalg.norm(df.values, ord=1, axis=1)

array([5., 3., 4.])

## KNN 구현

In [21]:
X, y = mglearn.datasets.make_forge()
print(X.shape)

NameError: name 'mglearn' is not defined

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=42)

print(len(X_train), len(X_test), len(y_train), len(y_test))

NameError: name 'X' is not defined

In [28]:
clf = KNeighborsClassifier(n_neighbors=11)
clf.fit(X_train, y_train)

NameError: name 'X_train' is not defined

In [29]:
print(clf.score(X_train, y_train))
print(clf.score(X_test, y_test))

NameError: name 'X_train' is not defined

In [30]:
clf.predict(X_test)

NameError: name 'X_test' is not defined

In [31]:
y_test

NameError: name 'y_test' is not defined

## 성능 분석에 대한 시각화

In [3]:
_. axes = plt.subplots(1,3, figsize=(10,3))
axes

for n, ax in zip([1,3,9], axes):
    clf = KNeighborsClassifier(n_neighbors=1).fit(X_train, y_train)
    mglearn.discrete_scatter(X[:,0],X[:, 1], y, ax=axes[0])
    mglearn.plots.plot_2d_seperator(clf,X,ax=axes[0], fill=True)
    axes[0].set_title("1개의 이웃" .format(n))

NameError: name 'plt' is not defined

## 유방암 데이터셋

In [5]:
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()
print(cancer.data)


[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3i random_state=42)

print(len(X_train), len(X_test), len(y_train), len(y_test))

SyntaxError: invalid decimal literal (781280344.py, line 1)

## 정규화를 하지 않았을 때

In [7]:
clf = KNeighborsClassifier(n_neighbors=5).fit(X_train, y_train)

NameError: name 'KNeighborsClassifier' is not defined

In [8]:
clf.score(X_train, y_train)
clf.score(X_test, y_tst)

NameError: name 'clf' is not defined

## 정규화를 했을 때


In [9]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train_normed = scaler.transform(X_train)
X_test_normed = scaler.transform(X_test)

NameError: name 'StandardScaler' is not defined

In [10]:
clf2 = KNeighborsClasifier(a_neighbors=5).fit(X_train_normed, y_train)

NameError: name 'KNeighborsClasifier' is not defined

## 가장 적합한 파라미터 선정

In [11]:
train_acc = []
test_acc = []

for n in range(1,12,2):
    clf = KNeighborsClassifier(n_neighbors=n).fit(X_train, y_train)
    
    train_acc.append

NameError: name 'KNeighborsClassifier' is not defined

## 신규 데이터 예측

In [16]:
new_data = pd.read_csv("C:\\pythonwork\\AI\\data_classification_cancer.csv")
new_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [17]:
new_data_normed = scaler.transform(new_data)

NameError: name 'scaler' is not defined

In [18]:
pred1 = clf2.predict(new_data_normed)
pred1

NameError: name 'clf2' is not defined

## 회귀 분석을 위한 KNN

In [19]:
X, y = mglearn.datasets.make_wave(n_samples=40)
mglearn.discrete_scatter(X[:, 0], y)

NameError: name 'mglearn' is not defined